### ISSUE TITLE
I can hijack accounts

### ISSUE THREAD

**Issue by timygerdes** [VladDrgm/Transcendence#214]
When I type in a url like 

https://transcendence-one.vercel.app/complete_profile?intraUsername=tge 
(After the equal sign can be anything that is not matching an existing users intraName in the DB)

- Type in a username
- Click on complete profile
- I get assigned a returned a random account from backend (I was logged in with Vlads, Madis and Domens acc)

**Comment by VladDrgm** [comment]
On the backend, the Get() endpoint for the callback needs to be changed, in order to add another layer of security somehow.

It can be found at pong_backend/src/modules/redirect/redirect.controller.ts .

I suspect the insertion has to happen on line 83 - 85 somewhere. In that 'if' condition, we should find a way to double check.

One idea I have is to turn the 'Get' function into something else ('Put', for example) and then send another payload from the frontend under the form of a body, hashed from the frontend, and then compare it in the backend and thus, you won't be able to hack your way into this without sending a body with the request (for which you need other tools, such as Postman or Swagger).

I can help today after 18:00 with this. Otherwise, if you think you can do it, feel free to get at it :) 


N.B - Please note that the changes suggested above will impact the frontend. This means that the calls from the frontend must be adjusted based on the changes in the backend.

**Comment by LidiaOrfanu** [comment]
TO BE FURTHER TESTED
For now if one tries to access http://localhost:3001/complete_profile?intraName=lorfanu  or http://localhost:3001/complete_profile?intraName=whatever without being logged properly beforehand it's being redirected to the login page
